### ISSUE TITLE
05장 질문 

### ISSUE THREAD

**Issue by yanJuicy** [yanJuicy-study/code-learn-spring-boot-web-project#1]
왜 `@ManyToOne` 을 사용해서 구현했을까요?
왜 `@OneToMany`를 사용하지 않았을까요?

**Comment by 404riot** [comment]
N:1의 형태에서 FK는 항상 N에 존재한다.
양방향이 되는 경우 N이 연관관계의 주인이 되고 member객체는 OneToMany(mappedBy = "board")를 가진다.
이 관계가 반대가 된다면 (member가 ManyToOne을 사용한다면)
member객체가 FK를 가지고 board가 PK를 가지게 된다. OneToMany(mappedBy = "member")

crud흐름상 회원이 생성된 후 게시물이 작성되는데 위와 같은 구조라면
회원이 회원가입을 할 때, 이 회원 객체는 참조할 PK가 없다. (아직 게시물이 생성되지 않았으니까.)
